remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - README.md
  - first-year/README.md
  - second-year/README.md
  - third-year/README.md
  - fourth-year/README.md

style: dark
listen_for_clients_preferred_style: false

footer: '©️ Managed by NCLSE, an edu-tech by Muhammad Istiqlal'
